# -*- coding: utf-8 -*-
"""A_estudiantes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R2UGyyeW08O0oKQRQLt5RqE-CpIJvIq4

https://raw.githubusercontent.com/JUAN-32/ETL-DATA-PIPELINE-25-0095-2022-/refs/heads/main/nootebooks/A_estudiantes.csv
"""

import pandas as pd

url="https://raw.githubusercontent.com/JUAN-32/ETL-DATA-PIPELINE-25-0095-2022-/refs/heads/main/nootebooks/A_estudiantes.csv"
df = pd.read_csv(url)
df.head()

#limpieza de datos

estudiantes = df.copy()

estudiantes.columns = estudiantes.columns.str.strip().str.lower()

for col in estudiantes.select_dtypes(include='object').columns:
    estudiantes[col] = estudiantes[col].astype(str).str.strip()

estudiantes = estudiantes.replace(r'^\s*$', pd.NA, regex=True)

estudiantes['id_estudiante'] = estudiantes['id_estudiante'].astype(str).str.upper().str.strip()

estudiantes['nombre'] = estudiantes['nombre'].replace(r'[^a-zA-ZáéíóúÁÉÍÓÚñÑ\s]', '', regex=True).str.strip()

estudiantes['edad'] = pd.to_numeric(estudiantes['edad'], errors='coerce')

estudiantes['correo'] = estudiantes['correo'].str.lower().str.strip()
estudiantes['correo'] = estudiantes['correo'].where(
    estudiantes['correo'].str.contains(r'^[\w\.-]+@[\w\.-]+\.\w+$', na=False),
    pd.NA
)

estudiantes = estudiantes.drop_duplicates(subset=['id_estudiante','nombre','edad','correo'])

#Separar datos válidos y rechazo
validos = estudiantes[
    estudiantes['id_estudiante'].notna() &
    estudiantes['nombre'].notna() &
    estudiantes['edad'].notna() &
    estudiantes['correo'].notna()
].copy()

rechazados = estudiantes[
    estudiantes['id_estudiante'].isna() |
    estudiantes['nombre'].isna() |
    estudiantes['edad'].isna() |
    estudiantes['correo'].isna()
].copy()

#motivo de rechazo
def motivo(row):
    motivos = []
    if pd.isna(row['id_estudiante']):
        motivos.append("id_vacio")
    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")
    if pd.isna(row['edad']):
        motivos.append("edad_vacia")
    if pd.isna(row['correo']):
        motivos.append("correo_vacio")
    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

#Exportar archivos
validos.to_csv("Estudiante_curated.csv", index=False)

rechazados.to_csv("Estudiante_rejects.csv", index=False)

df.shape
df.columns
df.info()
df.isnull().sum()

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd



database_url = "postgresql://juan:7RwRd1YakvKS4tuz3o1p6rzxu8niaaeG@dpg-d6qu7h4hg0os73b4gn0g-a.oregon-postgres.render.com/etl_seguros_hhfg"
engine = create_engine(database_url)

pd.read_sql("SELECT 1", engine)

validos.to_sql('estudiantes_curated', engine, if_exists='append', index=False)

rechazados.to_sql('estudiantes_rejects', engine, if_exists='append', index=False)

pd.read_sql("SELECT * FROM estudiantes_curated LIMIT 10", engine)