# -*- coding: utf-8 -*-
"""etl_A_notas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174lN-5j-Fl26x1au-1Ul1Gqw1W-EtmZd

https://raw.githubusercontent.com/JUAN-32/ETL-DATA-PIPELINE-25-0095-2022-/refs/heads/main/nootebooks/A_notas.csv
"""

import pandas as pd

url="https://raw.githubusercontent.com/JUAN-32/ETL-DATA-PIPELINE-25-0095-2022-/refs/heads/main/nootebooks/A_notas.csv"
df = pd.read_csv(url)
df.head()

#limpieza de datos
A_notas = df.copy()

A_notas.columns = A_notas.columns.str.strip().str.lower()

for col in A_notas.select_dtypes(include='object').columns:
    A_notas[col] = A_notas[col].astype(str).str.strip()

siniestros = A_notas.replace(r'^\s*$', pd.NA, regex=True)


A_notas['nota'] = A_notas['nota'].replace(['N/A', '0'], pd.NA)
A_notas['id_estudiante'] = A_notas['id_estudiante'].replace(['N/A', '-'], pd.NA)


A_notas['id_curso'] = A_notas['id_curso'].replace(['N/A', '-'], pd.NA)

A_notas['nota'] = A_notas['nota'].replace(['diez', '10'], pd.NA)
A_notas['nota'] = A_notas['nota'].astype(str).str.replace(",", "", regex=False)
A_notas['nota'] = pd.to_numeric(siniestros['nota'], errors='coerce')

#Separar datos válidos y rechazados
validos = A_notas[
    A_notas['nota'].notna() &
    A_notas['id_curso'].notna() &
      A_notas['periodo'].notna() &
     A_notas['id_estudiante'].notna()
].copy()

rechazados = A_notas[
    A_notas['nota'].isna() |
    A_notas['id_curso'].isna() |
    A_notas['periodo'].isna() |
     A_notas['id_estudiante'].isna()

].copy()

#Exportar archivos
validos.to_csv("A_notas_curated.csv", index=False)

rechazados.to_csv("A_notas_rejects.csv", index=False)

#motivo de rechazo
def motivo(row):
    motivos = []

    if pd.isna(row['nota']):
        motivos.append("nota_vacia")

    if pd.isna(row['id_curso']):
        motivos.append("monto_vacio")

    if pd.isna(row['periodo']):
        motivos.append("periodo_vacio")
    if pd.isna(row['id_estudiante']):
        motivos.append("estudiante_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

df.shape
df.columns
df.info()
df.isnull().sum()

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd



database_url = "postgresql://juan:7RwRd1YakvKS4tuz3o1p6rzxu8niaaeG@dpg-d6qu7h4hg0os73b4gn0g-a.oregon-postgres.render.com/etl_seguros_hhfg"
engine = create_engine(database_url)

pd.read_sql("SELECT 1", engine)

validos.to_sql('nota_curated', engine, if_exists='append', index=False)

rechazados.to_sql('nota_rejects', engine, if_exists='append', index=False)

pd.read_sql(
    "SELECT * FROM nota_curated LIMIT 10",
    engine
)