# -*- coding: utf-8 -*-
"""etl_A_Cursos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wbfK6OK8wz8M3LPdftizpvLwhomAx1-

https://raw.githubusercontent.com/JUAN-32/ETL-DATA-PIPELINE-25-0095-2022-/refs/heads/main/nootebooks/A_cursos.csv
"""

import pandas as pd

url="https://raw.githubusercontent.com/JUAN-32/ETL-DATA-PIPELINE-25-0095-2022-/refs/heads/main/nootebooks/A_cursos.csv"
df = pd.read_csv(url)
df.head()

#Limpieza de datos

A_cursos = df.copy()

A_cursos.columns = A_cursos.columns.str.strip().str.lower()

for col in A_cursos.select_dtypes(include='object').columns:
    A_cursos[col] = A_cursos[col].astype(str).str.strip()

A_cursos = A_cursos.replace(r'^\s*$', pd.NA, regex=True)

A_cursos['id_curso'] = A_cursos['id_curso'].replace(['N/A', '-'], pd.NA)

A_cursos['curso'] = A_cursos['curso'].replace(['N/A', '-'], pd.NA)

A_cursos['docente'] = A_cursos['docente'].replace(['N/A', '-'], pd.NA)

A_cursos['creditos'] = A_cursos['creditos'].replace(['N/A', '-', 'cr'], pd.NA)
A_cursos['creditos'] = A_cursos['creditos'].astype(str).str.replace("cr", "", regex=False)
A_cursos['creditos'] = A_cursos['creditos'].astype(str).str.replace(",", "", regex=False)
A_cursos['creditos'] = pd.to_numeric(A_cursos['creditos'], errors='coerce')

A_cursos = A_cursos.drop_duplicates(subset=['id_curso','curso','docente','creditos'])

#Separar datos válidos y rechazo
validos = A_cursos[
    A_cursos['id_curso'].notna() &
    A_cursos['curso'].notna() &
    A_cursos['docente'].notna() &
    A_cursos['creditos'].notna()
].copy()

rechazados = A_cursos[
    A_cursos['id_curso'].isna() |
    A_cursos['curso'].isna() |
    A_cursos['docente'].isna() |
    A_cursos['creditos'].isna()
].copy()

#Separar datos válidos y rechazados
validos = A_cursos[
    A_cursos['id_curso'].notna() &
    A_cursos['curso'].notna() &
    A_cursos['docente'].notna() &
    A_cursos['creditos'].notna()
].copy()

rechazados = A_cursos[
    A_cursos['id_curso'].isna() |
    A_cursos['curso'].isna() |
    A_cursos['docente'].isna() |
    A_cursos['creditos'].isna()
].copy()

#motivo de rechazo
def motivo(row):
    motivos = []
    if pd.isna(row['id_curso']):
        motivos.append("id_vacio")
    if pd.isna(row['curso']):
        motivos.append("curso_vacio")
    if pd.isna(row['docente']):
        motivos.append("docente_vacio")
    if pd.isna(row['creditos']):
        motivos.append("creditos_vacio")
    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

#Exportar archivos
validos.to_csv("Cursos_curated.csv", index=False)

rechazados.to_csv("Cursos_rejects.csv", index=False)

df.shape
df.columns
df.info()
df.isnull().sum()

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd



database_url = "postgresql://juan:7RwRd1YakvKS4tuz3o1p6rzxu8niaaeG@dpg-d6qu7h4hg0os73b4gn0g-a.oregon-postgres.render.com/etl_seguros_hhfg"
engine = create_engine(database_url)

pd.read_sql("SELECT 1", engine)

validos.to_sql('curso_curated', engine, if_exists='append', index=False)

rechazados.to_sql('curso_rejects', engine, if_exists='append', index=False)

pd.read_sql("SELECT * FROM curso_curated LIMIT 10", engine)